### PR TITLE
Add Sway support

### PR DESCRIPTION
**Pull request by jamespeapen**
Since sway supports i3 syntax, it would be nice to have support for the config files. I've added support for sway config file detection. There is also support for the `include` keyword to load sway files that is not a part of i3.
Thanks for the plugin!

### CODE REVIEW

**Comment by mboughaba** [comment]
@jamespeapen it looks nice to me, thanks 
do you wanna re-open it?

**Comment by jamespeapen** [comment]
I made a new fork with more changes and thought it would be better as a different repository. 
Thanks for looking into it though!

**Comment by hiqua** [comment]
@jamespeapen I just saw your fork, consider contributing to the Vim repository directly so that every Vim user gets your improvements out of the box! I juste created a PR to merge @mboughaba's version, but you can easily add your changes on top once it's in.

**Comment by jamespeapen** [comment]
@hiqua  Thanks for looking into this! Do you think a new syntax file just for sway would be good or should it be merged into this repo? Most of the changes I made involve changing occurences of i3 to sway and adding sway-specific keywords. 
UPDATE: I made a pull request with sway support in this repo

**Pull request closed without merging**
